addons:
  postgresql: "9.6"
  apt:
    packages: oracle-java8-installer
language: java
services: postgresql
before_script:
  - psql -c 'CREATE DATABASE billing' -U postgres
  - cd migrations
  - mvn clean initialize flyway:migrate -Dpostgres.password=''
  - cd ..
install: true
script: mvn clean install -Dpostgres.password=''
