language: java
services: postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
    - oracle-java8-installer

before_script:
- psql -c 'CREATE DATABASE billing' -U postgres
- mvn -P migration initialize flyway:migrate -Dpostgres.password=''

install: true
script: mvn clean install -Dpostgres.password=''