addons:
  postgresql: "9.6"
  apt:
    packages: oracle-java8-installer
language: java
services: postgresql
install: true
before_script:
  - psql -c 'create database billing;' -U postgres
  - cd migrations && mvn clean initialize flyway:migrate -Dpostgres.url='jdbc:postgresql://localhost:5432/billing' -Dpostgres.username='postgres' -Dpostgres.password=''
script: mvn clean install -Dpostgres.url='jdbc:postgresql://localhost:5432/billing' -Dpostgres.username='postgres' -Dpostgres.password=''
