swagger: "2.0"

info:
  title: Aplatanao Billing Service
  description: Implementation of the Aplatanao Billing Service.
  version: 1.0.0
  license:
    name: MIT License

host: localhost:8080
basePath: /api
schemes:
  - http

paths:

  /invoices:
    description: Invoices

    get:
      operationId: getInvoices
      summary: Returns a list of invoices.
      produces:
      - application/json
      parameters:
      - $ref: "#/parameters/Page"
      - $ref: "#/parameters/Size"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Invoices"
        500:
          description: Error
          schema:
            $ref: '#/definitions/Error'

    post:
      operationId: addInvoice
      summary: Creates a new invoice.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/Invoice"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Invoice"
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        403:
          description: Forbidden
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Error
          schema:
            $ref: '#/definitions/Error'

  /invoice/{id}:
    description: Invoice

    get:
      operationId: getInvoiceById
      summary: Find invoice by ID.
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: ID of invoice to return.
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Invoice"
        404:
          description: Not Found
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Error
          schema:
            $ref: '#/definitions/Error'

parameters:

  Page:
    name: page
    description: Page to return.
    in: query
    required: true
    type: integer
    format: int32
    default: 0
    minimum: 0

  Size:
    name: size
    description: Number of records to page.
    in: query
    required: true
    type: integer
    format: int32
    default: 20

definitions:

  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"

  Invoice:
    type: "object"
    required:
    - "date"
    - "code"
    properties:
      id:
        type: "integer"
        format: "int64"
      date:
        type: "string"
        format: "date"
      code:
        type: "string"
      comment:
        type: "string"

  Invoices:
    type: "array"
    items:
      $ref: '#/definitions/Invoice'