swagger: 2.0

info:
  title: Aplatanao Billing Service
  description: API of the Aplatanao Billing Service.
  version: 1.0.0
  license:
    name: MIT License

host: localhost:8080
basePath: /api
schemes:
  - http
  - https

paths:

  /invoices:
    description: Invoices resource.

    get:
      operationId: getInvoices
      summary: Return a paged invoice list.
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/Page'
      - $ref: '#/parameters/Size'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Invoices'
        500:
          description: Error
          schema:
            $ref: '#/definitions/Error'

    post:
      operationId: addInvoice
      summary: Add a new invoice.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Invoice'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Invoice'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Validation'
        500:
          description: Error
          schema:
            $ref: '#/definitions/Error'

  /invoices/{code}:

    get:
      operationId: getInvoiceByCode
      summary: Get an invoice by code.
      produces:
      - application/json
      parameters:
      - name: code
        in: path
        description: Code of the invoice to return.
        required: true
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Invoice'
        404:
          description: Not Found
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Error
          schema:
            $ref: '#/definitions/Error'

  /reports:
    description: Reports resource.

  /reports/invoices/{year}:
    get:
      operationId: getInvoicesPerMonth
      summary: Get invoices report.
      produces:
      - application/json
      parameters:
      - name: year
        in: path
        description: Year of invoices to be analyzed.
        required: true
        type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/InvoicesPerMonth'
        500:
          description: Error
          schema:
            $ref: '#/definitions/Error'

parameters:

  Page:
    name: page
    description: The page to be returned.
    in: query
    required: true
    type: integer
    format: int32
    default: 0
    minimum: 0

  Size:
    name: size
    description: Number of records to be returned.
    in: query
    required: true
    type: integer
    format: int32
    default: 20

definitions:

  Error:
    description: Generic uncaught error.
    type: object
    properties:
      status:
        description: HTTP status code.
        type: integer
        format: int32
      message:
        type: string

  Validation:
    description: Input validation error with detailed explainations.
    type: object
    properties:
      status:
        description: HTTP status code.
        type: integer
        format: int32
      messages:
        description: Validation hints mapped by input hierarchy.
        type: object
        additionalProperties:
          type: string

  InvoicePosition:
    type: object
    required:
    - number
    - amount
    - description
    properties:
      number:
        type: integer
        format: int32
      amount:
        type: number
      description:
        type: string

  Invoice:
    type: object
    required:
    - code
    - date
    properties:
      code:
        type: string
      date:
        type: string
        format: date
      comment:
        type: string
      positions:
        type: array
        items:
          $ref: '#/definitions/InvoicePosition'

  Invoices:
    type: array
    items:
      $ref: '#/definitions/Invoice'

  InvoicesPerMonth:
    type: array
    items:
      type: object
      required:
      - year
      - month
      - count
      - amount
      properties:
        year:
          type: integer
        month:
          type: integer
        count:
          type: integer
        amount:
          type: number
