swagger: '2.0'
info:
  title: Aplatanao Billing Service
  description: API of the Aplatanao Billing Service.
  version: 1.0.0
  license:
    name: MIT License
schemes:
  - http
  - https
host: 'localhost:8080'
basePath: /api
produces:
  - application/json
paths:
  /invoices:
    get:
      summary: Paged invoice list.
      operationId: getInvoices
      parameters:
        - $ref: '#/parameters/Page'
        - $ref: '#/parameters/Size'
        - $ref: '#/parameters/YearQuery'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Invoices'
        '500':
          description: Error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Add a new invoice.
      operationId: addInvoice
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Invoice'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/TaskReference'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Validation'
        '500':
          description: Error
          schema:
            $ref: '#/definitions/Error'
  '/invoices/approvals':
    post:
      summary: Complete an invoice approval task.
      operationId: approveInvoice
      consumes:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/InvoiceApproval'
      responses:
        '201':
          description: Created (saved)
          schema:
            $ref: '#/definitions/InvoiceReference'
        '204':
          description: No Content (rejected)
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Validation'
        '500':
          description: Error
          schema:
            $ref: '#/definitions/Error'
  '/invoices/{uuid}':
    parameters:
      - $ref: '#/parameters/UUID'
    get:
      summary: Get an invoice by UUID.
      operationId: getInvoiceByUUID
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Invoice'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Error
          schema:
            $ref: '#/definitions/Error'
  '/reports/invoices/{year}':
    parameters:
      - $ref: '#/parameters/YearPath'
    get:
      summary: Get invoices report.
      operationId: getInvoicesPerMonth
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/InvoicesPerMonth'
        '500':
          description: Error
          schema:
            $ref: '#/definitions/Error'
  '/payments':
    get:
      summary: Paged payment list.
      operationId: getPayments
      parameters:
        - $ref: '#/parameters/Page'
        - $ref: '#/parameters/Size'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Payments'
        '500':
          description: Error
          schema:
            $ref: '#/definitions/Error'
  '/tasks':
    get:
      summary: Paged process task list.
      operationId: getTasks
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Tasks'
        '500':
          description: Error
          schema:
            $ref: '#/definitions/Error'
parameters:
  UUID:
    description: UUID of the resource to be returned.
    required: true
    in: path
    name: uuid
    type: string
    format: uuid4
    pattern: '^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[4][0-9a-fA-F]{3}\-[89abAB][0-9a-fA-F]{3}\-[0-9a-fA-F]{12}$'
  Page:
    description: The page to be returned.
    in: query
    name: page
    required: true
    type: integer
    format: int32
    default: 0
    minimum: 0
  Size:
    description: Number of records to be returned.
    required: true
    in: query
    name: size
    type: integer
    format: int32
    default: 20
    minimum: 5
  YearPath:
    description: Year of resources to be returned.
    required: true
    in: path
    name: year
    type: integer
    format: int32
    minimum: 1978
    maximum: 32767
  YearQuery:
    description: Year to filter a resource.
    required: true
    in: query
    name: year
    type: integer
    format: int32
    minimum: 1978
    maximum: 32767
definitions:
  Error:
    description: Generic API error.
    type: object
    required:
      - code
      - status
      - message
    properties:
      code:
        description: HTTP status code.
        type: integer
        format: int32
        minimum: 100
        maximum: 599
      status:
        description: HTTP status reason phrase.
        type: string
      message:
        description: Error message.
        type: string
  Validation:
    description: Input validation error with detailed explainations.
    allOf:
      - $ref: '#/definitions/Error'
      - type: object
        properties:
          messages:
            description: Validation hints mapped by input hierarchy.
            type: object
            additionalProperties:
              type: string
  InvoiceReference:
    description: Invoice reference.
    type: object
    required:
    - uuid
    - code
    - date
    properties:
      uuid:
        type: string
        format: uuid4
        readOnly: true
      code:
        type: string
        minLength: 3
        maxLength: 20
      date:
        type: string
        format: date
  InvoiceApproval:
    description: Invoice approval.
    type: object
    required:
    - uuid
    - approved
    properties:
      uuid:
        type: string
        format: uuid4
        readOnly: true
      approved:
        type: boolean
  InvoicePosition:
    description: Invoice position.
    type: object
    required:
      - description
      - cents
    properties:
      created_at:
        type: string
        format: date-time
        readOnly: true
      description:
        type: string
      cents:
        type: integer
        format: int64
  Invoice:
    description: Invoice.
    type: object
    required:
      - code
      - date
    properties:
      uuid:
        type: string
        format: uuid4
        readOnly: true
      created_at:
        type: string
        format: date-time
        readOnly: true
      code:
        type: string
        minLength: 3
        maxLength: 20
      date:
        type: string
        format: date
      comment:
        type: string
      positions:
        type: array
        items:
          $ref: '#/definitions/InvoicePosition'
  Invoices:
    description: Invoice list.
    type: array
    items:
      $ref: '#/definitions/Invoice'
  InvoicesPerMonth:
    description: Invoice per month report of a year.
    type: array
    items:
      type: object
      required:
        - year
        - month
        - count
        - cents
      properties:
        year:
          type: integer
          format: int32
          minimum: 1978
          maximum: 32767
        month:
          type: integer
          format: int32
          minimum: 1
          maximum: 12
        count:
          type: integer
          format: int64
          minimum: 0
        cents:
          type: integer
          format: int64
  Payment:
    description: Payment.
    type: object
    required:
      - code
      - date
      - cents
    properties:
      uuid:
        type: string
        format: uuid4
        readOnly: true
      created_at:
        type: string
        format: date-time
        readOnly: true
      code:
        type: string
        minLength: 3
        maxLength: 20
      date:
        type: string
        format: date
      comment:
        type: string
      cents:
        type: integer
        format: int64
  Payments:
    description: Payment list.
    type: array
    items:
      $ref: '#/definitions/Payment'
  TaskReference:
    description: Process task reference.
    type: object
    required:
    - uuid
    properties:
      uuid:
        type: string
        format: uuid4
        readOnly: true
      dueDate:
        type: string
        format: date
      description:
        type: string
  Task:
    description: Process task.
    type: object
    required:
      - uuid
      - name
      - key
      - priority
    properties:
      uuid:
        type: string
        format: uuid4
        readOnly: true
      name:
        type: string
      key:
        type: string
      priority:
        type: integer
        format: int32
      dueDate:
        type: string
        format: date
      description:
        type: string
  Tasks:
    description: Process task list.
    type: array
    items:
      $ref: '#/definitions/Task'